### ISSUE TITLE
Add an "translate" command

### ISSUE THREAD

**Issue by Peter-developer01** [PlaceReporter99/utility-bot#31]
I suggest adding an `translate` command.

The command will take some text. Then it will take first argument as original language, second argument as translate-to language, and every other as the text to translate.

I have code for it, you can tweak it for your needs. But maybe you know better translation service.

Well, how's the idea?

**Comment by PlaceReporter99** [comment]
It might not be implemented exactly the way you described it.

**Comment by Peter-developer01** [comment]
> It might not be implemented exactly the way you described it.

Yeah I understand, that's even nicer.

**Comment by PlaceReporter99** [comment]
@Peter-developer01 the `translate` command has been added! Supported languages and the codes you must use for them are listed [here]( https://placereporter99.github.io/utility-bot/supported-langs/). If there are any bugs, feel free to open another issue!

**Comment by Peter-developer01** [comment]
@PlaceReporter99 Thanks. Will test now.
