### ISSUE TITLE
Streamlit doesn't work

### ISSUE THREAD

**Issue by Peter-developer01** [PlaceReporter99/utility-bot#75]
![image](https://github.com/PlaceReporter99/utility-bot/assets/101456132/bc9f85df-97f6-4d2c-b140-e100bde9c039)

**Comment by Peter-developer01** [comment]
Streamlit now works properly.

**Comment by PlaceReporter99** [comment]
@Peter-developer01 just click "Yes, get this app back up!"

**Comment by Peter-developer01** [comment]
@PlaceReporter99 I got this already
